name: teste_flash_courier
description: Desafio para o processo seletivo da Flash Courier

#
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  animated_splash_screen: ^1.3.0
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.8
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.8
  brasil_fields: ^1.5.0
  permission_handler: ^10.0.1
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.1.1
  provider: ^6.0.3
  firebase_messaging: ^13.0.3
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^9.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/logo.png

